import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { UserProgress, RecordAttemptDto, StudyStats } from '@kasita/common-models';

export const UserProgressActions = createActionGroup({
  source: 'UserProgress API',
  events: {
    'Select UserProgress': props<{ selectedId: string }>(),
    'Reset Selected UserProgress': emptyProps(),
    'Reset UserProgress': emptyProps(),
    'Load UserProgress': emptyProps(),
    'Load UserProgress Success': props<{ userProgress: UserProgress[] }>(),
    'Load UserProgress Failure': props<{ error: string | null }>(),
    'Load UserProgress Item': props<{ userProgressId: string }>(),
    'Load UserProgress Item Success': props<{ userProgress: UserProgress }>(),
    'Load UserProgress Item Failure': props<{ error: string | null }>(),
    'Create UserProgress': props<{ userProgress: UserProgress }>(),
    'Create UserProgress Success': props<{ userProgress: UserProgress }>(),
    'Create UserProgress Failure': props<{ error: string | null }>(),
    'Update UserProgress': props<{ userProgress: UserProgress }>(),
    'Update UserProgress Success': props<{ userProgress: UserProgress }>(),
    'Update UserProgress Failure': props<{ error: string | null }>(),
    'Delete UserProgress': props<{ userProgress: UserProgress }>(),
    'Delete UserProgress Success': props<{ userProgress: UserProgress }>(),
    'Delete UserProgress Failure': props<{ error: string | null }>(),
    'Delete UserProgress Cancelled': emptyProps(),
    'Upsert UserProgress': props<{ userProgress: UserProgress }>(),
    'Upsert UserProgress Success': props<{ userProgress: UserProgress }>(),
    'Upsert UserProgress Failure': props<{ error: string | null }>(),
    // Study actions
    'Record Attempt': props<{ attempt: RecordAttemptDto }>(),
    'Record Attempt Success': props<{ userProgress: UserProgress }>(),
    'Record Attempt Failure': props<{ error: string | null }>(),
    'Load Due For Review': props<{ userId: string }>(),
    'Load Due For Review Success': props<{ userProgress: UserProgress[] }>(),
    'Load Due For Review Failure': props<{ error: string | null }>(),
    'Load Study Stats': props<{ userId: string }>(),
    'Load Study Stats Success': props<{ stats: StudyStats }>(),
    'Load Study Stats Failure': props<{ error: string | null }>(),
    'Load User Progress By User': props<{ userId: string }>(),
    'Load User Progress By User Success': props<{ userProgress: UserProgress[] }>(),
    'Load User Progress By User Failure': props<{ error: string | null }>(),
  },
});
