import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  ApplicationConfig,
  ErrorHandler,
  isDevMode,
} from '@angular/core';
import { provideSignalFormsConfig } from '@angular/forms/signals';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';
import { API_URL, authInterceptor, errorInterceptor, GlobalErrorHandler } from '@kasita/core-data';
import {
  challengesFeature,
  checkEnrollment,
  createChallenge,
  createDataSource,
  createKnowledgeUnit,
  createLearningPath,
  createPrinciple,
  createProject,
  createRawContent,
  createSubmission,
  createUser,
  createUserProgress,
  dataSourcesFeature,
  deleteChallenge,
  deleteDataSource,
  deleteKnowledgeUnit,
  deleteLearningPath,
  deletePrinciple,
  deleteProject,
  deleteRawContent,
  deleteSubmission,
  deleteUser,
  deleteUserProgress,
  enroll,
  enrollmentsFeature,
  knowledgeUnitsFeature,
  learningPathsFeature,
  linkPrinciple,
  loadChallenge,
  // Challenges Effects
  loadChallenges,
  loadChallengesByUnit,
  loadDataSource,
  // Data Sources Effects
  loadDataSources,
  // Enrollments Effects
  loadEnrollments,
  loadEnrollmentsByPath,
  loadEnrollmentsByUser,
  loadFeedback,
  loadKnowledgeUnit,
  // Knowledge Units Effects
  loadKnowledgeUnits,
  loadKnowledgeUnitsByPath,
  loadLeaderboard,
  loadLearningPath,
  // Learning Paths Effects
  loadLearningPaths,
  loadMentorSubmissions,
  loadPrinciple,
  // Principles Effects
  loadPrinciples,
  loadPrinciplesByPath,
  loadProject,
  // Projects Effects
  loadProjects,
  loadProjectsByPath,
  // Raw Content Effects
  loadRawContent,
  loadRawContentByPath,
  loadRawContentItem,
  loadSubmission,
  // Submissions Effects
  loadSubmissions,
  loadSubmissionsByPath,
  loadSubmissionsByUnit,
  loadSubmissionsByUser,
  loadUser,
  // User Progress Effects
  loadUserProgress,
  loadUserProgressItem,
  // Users Effects
  loadUsers,
  principlesFeature,
  projectsFeature,
  rawContentFeature,
  requestAiFeedback,
  submissionsFeature,
  submitForReview,
  submitMentorFeedback,
  unenroll,
  unlinkPrinciple,
  updateChallenge,
  updateDataSource,
  updateEnrollment,
  updateKnowledgeUnit,
  updateLearningPath,
  updatePrinciple,
  updateProject,
  updateRawContent,
  updateSubmission,
  updateUser,
  updateUserProgress,
  userProgressFeature,
  usersFeature,
  // Gymnasium
  gymnasiumFeature,
  loadSessions,
  loadPublicSessions,
  loadSession,
  renderSession,
  createGymnasiumSession,
  updateGymnasiumSession,
  deleteGymnasiumSession,
  publishSession,
  unpublishSession,
  generateSession,
  loadTemplates,
  loadDefaultTemplate,
} from '@kasita/core-state';
import { provideEffects } from '@ngrx/effects';
import { provideStore } from '@ngrx/store';
import { provideStoreDevtools } from '@ngrx/store-devtools';

import { environment } from '../environments/environment';
import { appRoutes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimations(), // Enable Angular animations (deprecated but still required for @ animations)
    provideRouter(appRoutes),
    provideHttpClient(withInterceptors([errorInterceptor, authInterceptor])),
    provideSignalFormsConfig({}),
    { provide: API_URL, useValue: environment.apiUrl },
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    // NgRx Store Configuration
    provideStore({
      learningPaths: learningPathsFeature.reducer,
      knowledgeUnits: knowledgeUnitsFeature.reducer,
      principles: principlesFeature.reducer,
      rawContent: rawContentFeature.reducer,
      userProgress: userProgressFeature.reducer,
      dataSources: dataSourcesFeature.reducer,
      users: usersFeature.reducer,
      submissions: submissionsFeature.reducer,
      challenges: challengesFeature.reducer,
      projects: projectsFeature.reducer,
      enrollments: enrollmentsFeature.reducer,
      gymnasium: gymnasiumFeature.reducer,
    }),
    provideEffects({
      // Learning Paths
      loadLearningPaths,
      loadLearningPath,
      createLearningPath,
      updateLearningPath,
      deleteLearningPath,
      // Knowledge Units
      loadKnowledgeUnits,
      loadKnowledgeUnit,
      loadKnowledgeUnitsByPath,
      createKnowledgeUnit,
      updateKnowledgeUnit,
      deleteKnowledgeUnit,
      // Principles
      loadPrinciples,
      loadPrinciple,
      loadPrinciplesByPath,
      createPrinciple,
      updatePrinciple,
      deletePrinciple,
      // Raw Content
      loadRawContent,
      loadRawContentItem,
      loadRawContentByPath,
      createRawContent,
      updateRawContent,
      deleteRawContent,
      // User Progress
      loadUserProgress,
      loadUserProgressItem,
      createUserProgress,
      updateUserProgress,
      deleteUserProgress,
      // Data Sources
      loadDataSources,
      loadDataSource,
      createDataSource,
      updateDataSource,
      deleteDataSource,
      // Users
      loadUsers,
      loadUser,
      createUser,
      updateUser,
      deleteUser,
      // Submissions
      loadSubmissions,
      loadSubmission,
      loadSubmissionsByUser,
      loadSubmissionsByUnit,
      loadSubmissionsByPath,
      createSubmission,
      updateSubmission,
      deleteSubmission,
      submitForReview,
      requestAiFeedback,
      loadFeedback,
      loadMentorSubmissions,
      submitMentorFeedback,
      // Challenges
      loadChallenges,
      loadChallenge,
      loadChallengesByUnit,
      createChallenge,
      updateChallenge,
      deleteChallenge,
      // Projects
      loadProjects,
      loadProject,
      loadProjectsByPath,
      createProject,
      updateProject,
      deleteProject,
      linkPrinciple,
      unlinkPrinciple,
      // Enrollments
      loadEnrollments,
      loadEnrollmentsByUser,
      loadEnrollmentsByPath,
      checkEnrollment,
      enroll,
      updateEnrollment,
      unenroll,
      loadLeaderboard,
      // Gymnasium
      loadSessions,
      loadPublicSessions,
      loadSession,
      renderSession,
      createGymnasiumSession,
      updateGymnasiumSession,
      deleteGymnasiumSession,
      publishSession,
      unpublishSession,
      generateSession,
      loadTemplates,
      loadDefaultTemplate,
    }),
    provideStoreDevtools({
      maxAge: 25,
      logOnly: !isDevMode(),
      autoPause: false, // Disabled to prevent issues with browser devtools open
      trace: false,
      traceLimit: 75,
    }),
  ],
};
